project_file = {
    "descriptions":[
        "README.md",
    ],
    "entry_points":[
        "main.py",
        "run.py",
        "app.py",
        "wsgi.py",
        "server.py",
        "manage.py",
    ],
    "dependencies":[
        "requirements.txt",
        "requirements-dev.txt",
    ],
    "configurations":[
        "config.py",
        "setup.py",
        ".env.example",
        "pyproject.toml",
    ],
}